// Build step: inline the shared browser helpers into the page templates and
// emit src/generated/pages.js (imported by src/worker.js). This is how the plan
// keeps a SINGLE source of truth for the crypto helpers (§16) — the same
// src/crypto.js runs in the phone sender, the car view, and the pairing pages,
// inlined rather than copy-pasted.
//
// Wrangler runs this via `[build] command` before every deploy/dev; `npm test`
// runs it via `pretest`. No external dependencies — plain Node fs.

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { dirname, join, basename } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, "src");
const PAGES_DIR = join(SRC, "pages");
const OUT_DIR = join(SRC, "generated");

// Turn an ES module of helpers into plain browser script: drop `export`/`import`
// lines so the declarations land directly in the page's script scope.
function inlinable(file) {
  return readFileSync(join(SRC, file), "utf8")
    .replace(/^export\s+/gm, "")
    .replace(/^import\s.*$/gm, "");
}

const CRYPTO = inlinable("crypto.js");
const QR = inlinable("qr.js");
const NAV = inlinable("navschemes.js");

// page file -> exported constant name in generated/pages.js
const PAGE_EXPORTS = {
  "car.html": "CAR_HTML",
  "send.html": "SEND_HTML",
  "pair.html": "PAIR_HTML",
  "vault.html": "VAULT_HTML",
  "nav-benchmark.html": "NAV_BENCHMARK_HTML",
};

function inlineHelpers(html, name) {
  let out = html;
  if (out.includes("/*__INLINE_CRYPTO__*/")) {
    out = out.replace("/*__INLINE_CRYPTO__*/", () => CRYPTO);
  }
  if (out.includes("/*__INLINE_QR__*/")) {
    out = out.replace("/*__INLINE_QR__*/", () => QR);
  }
  if (out.includes("/*__INLINE_NAV__*/")) {
    out = out.replace("/*__INLINE_NAV__*/", () => NAV);
  }
  // Catch typos: a leftover INLINE token means a helper never got injected.
  const leftover = out.match(/\/\*__INLINE_[A-Z]+__\*\//);
  if (leftover) throw new Error(`${name}: unresolved placeholder ${leftover[0]}`);
  return out;
}

mkdirSync(OUT_DIR, { recursive: true });

const present = readdirSync(PAGES_DIR).filter((f) => f.endsWith(".html"));
let module = "// AUTO-GENERATED by build.mjs — do not edit. Run `npm run build`.\n\n";
const built = [];

for (const [file, exportName] of Object.entries(PAGE_EXPORTS)) {
  if (!present.includes(file)) {
    throw new Error(`Missing page template: src/pages/${file}`);
  }
  const html = readFileSync(join(PAGES_DIR, file), "utf8");
  const final = inlineHelpers(html, file);
  module += `export const ${exportName} = ${JSON.stringify(final)};\n`;
  built.push(`${file} -> ${exportName} (${final.length}B)`);
}

writeFileSync(join(OUT_DIR, "pages.js"), module);
console.log("build: wrote src/generated/pages.js");
for (const line of built) console.log("  " + line);
